### ISSUE TITLE
Error when loading FlyingThings3D

### ISSUE THREAD

**Issue by ZhangYushan3** [MCG-NJU/CamLiFlow#10]
Hi, thanks for the nice work. But I got the following error when loading the FlyingThings3D subset after preprocessing. I've checked that the pcs actually are 0 length. Do you have any idea why I got this error and how to fix it? Thanks.

Traceback (most recent call last):
  File "main.py", line 554, in <module>
    main(args)
  File "main.py", line 301, in main
    for i, sample in enumerate(train_loader):
  File "/mimer/NOBACKUP/groups/alvis_cvl/yushanz/miniconda3/envs/sceneflow/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/mimer/NOBACKUP/groups/alvis_cvl/yushanz/miniconda3/envs/sceneflow/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/mimer/NOBACKUP/groups/alvis_cvl/yushanz/miniconda3/envs/sceneflow/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/mimer/NOBACKUP/groups/alvis_cvl/yushanz/miniconda3/envs/sceneflow/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/mimer/NOBACKUP/groups/alvis_cvl/yushanz/miniconda3/envs/sceneflow/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/mimer/NOBACKUP/groups/alvis_cvl/yushanz/miniconda3/envs/sceneflow/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mimer/NOBACKUP/groups/alvis_cvl/yushanz/miniconda3/envs/sceneflow/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mimer/NOBACKUP/groups/alvis_cvl/yushanz/scene_flow/sceneflow/dataloader/flyingthings3d.py", line 65, in __getitem__
    indices2 = np.random.choice(pc2.shape[0], size=self.n_points, replace=pc2.shape[0] < self.n_points)
  File "mtrand.pyx", line 909, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken

**Comment by afterthat97** [comment]
It looks strange. Can you check the depth range of the point clouds?

**Comment by ZhangYushan3** [comment]
Thanks. I did something wrong in the augmentation. Now it's fixed.
